set -o vi

C_RED='\[\033[01;31m\]'
C_BLD='\[\033[1m\]'
C_NUL='\[\033[00m\]'

if [[ -n $SSH_CLIENT ]]; then
	export PROMPT_COMMAND='echo -ne "\033]0;${HOSTNAME} \007" && history -a'
fi

case "$TERM" in
xterm*|rxvt*|screen*)
	PS1="$C_RED\\h $C_NUL$C_BLD#$C_NUL "
	;;
esac

pathdirs=(
	"$HOME/bin"
	'/opt/local/sbin'
	'/opt/local/bin'
	'/usr/sbin'
	'/usr/bin'
	'/sbin'
)
export PATH=$(IFS=':'; printf '%s' "${pathdirs[*]}")
